### ISSUE TITLE
Refactor Program class

### ISSUE THREAD

**Issue by sschaub** [runnersQueue/3minutes#2]
* Start() is a big method. Pull out the code that sets up the menu into a separate method.
* You have several boolean flags . Consider whether an enumerated variable and a basic state machine would simplify some of your logic for keeping track of whether you're playing the game, at the end of the level, etc.

**Comment by CarSan64** [comment]
Start() has been refactored, with specific blocks of text appearing in distinct methods. Those methods are then called in Start(). Some code that could not be refactored remains free in Start(). Functionality has not been altered as of April 11.
